// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// A10Error is an autogenerated mock type for the A10Error type
type A10Error struct {
	mock.Mock
}

// Code provides a mock function with given fields:
func (_m *A10Error) Code() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Error provides a mock function with given fields:
func (_m *A10Error) Error() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Message provides a mock function with given fields:
func (_m *A10Error) Message() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
