// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import model "a10bridge/model"

// HealthCheckProcessor is an autogenerated mock type for the HealthCheckProcessor type
type HealthCheckProcessor struct {
	mock.Mock
}

// ProcessHealthCheck provides a mock function with given fields: healthCheck
func (_m *HealthCheckProcessor) ProcessHealthCheck(healthCheck *model.HealthCheck) error {
	ret := _m.Called(healthCheck)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.HealthCheck) error); ok {
		r0 = rf(healthCheck)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
